### ISSUE TITLE
Game over when a viable placement has just been cleared.

### ISSUE THREAD

**Issue by casperlehmann** [RedXBeard/kivy-1010#1]
I downloaded the dmg-file. Am running on Mavericks.

![screen shot 2015-02-25 at 18 43 00 2](https://cloud.githubusercontent.com/assets/6682833/6369210/e91136d0-bd1e-11e4-8f3e-fe2fc86b596f.png)

**Comment by RedXBeard** [comment]
Hello, 
Did you run the code from source or from dmg ? If from source, which version of Kivy did you install ? which operating system are you using ? because this was solved earlier.

**Comment by casperlehmann** [comment]
Sorry, completely forgot to post details. I updated the post.

**Comment by RedXBeard** [comment]
Thank you, problem will be solved as quick as possible.

**Comment by RedXBeard** [comment]
thank you, 
https://github.com/RedXBeard/kivy-1010/pull/5
