### ISSUE TITLE
Rotation is not reset between turns.

### ISSUE THREAD

**Issue by casperlehmann** [RedXBeard/kivy-1010#2]
Turning a tile at an angle affects the tile in the corresponding position during the next turn.
I downloaded the dmg-file. Am running on Mavericks.

![screen shot 2015-02-25 at 18 55 43](https://cloud.githubusercontent.com/assets/6682833/6369324/24162398-bd20-11e4-9e37-e896cb3fa57f.png)
![screen shot 2015-02-25 at 18 55 57](https://cloud.githubusercontent.com/assets/6682833/6369323/23a85dea-bd20-11e4-8252-569f4e08d290.png)

**Comment by RedXBeard** [comment]
hi, rotation was disabled, how did you rotate again, would you give some info for that to fix?

**Comment by casperlehmann** [comment]
I left clicked on the figure (two finger tap), to open Kivy's multitouch emulation.
The red dot signifies one finger, your mouse then takes the role of the second finger.
Once again, I used the dmg-download on Mavericks.

![screen shot 2015-02-25 at 20 22 14](https://cloud.githubusercontent.com/assets/6682833/6370482/04961eea-bd2c-11e4-8fb4-33a74ffc9cd3.png)

**Comment by RedXBeard** [comment]
Thank you, that will be fixed as soon as possible

**Comment by RedXBeard** [comment]
https://github.com/RedXBeard/kivy-1010/pull/4
