### ISSUE TITLE
Right click and Middle click problem

### ISSUE THREAD

**Issue by nerezo** [RedXBeard/kivy-1010#3]
When I click on right or middle mouse button over a shape it scales up/down and does not turn to how that came at the first time. Then next shapes seem scaled like that.

![kivy 1010_016](https://cloud.githubusercontent.com/assets/6855592/6370292/5a49a5b2-bcf7-11e4-8a51-c82f0622d4d4.png)

**Comment by RedXBeard** [comment]
Thank you, will be fixed soon.

**Comment by nerezo** [comment]
I forgot to mention that it runs on a 64-bit Ubuntu 14.04 LTS installation.

**Comment by RedXBeard** [comment]
https://github.com/RedXBeard/kivy-1010/pull/4
